# Generated by Django 3.1.4 on 2021-01-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=20)),
                ('method', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
