# Generated by Django 3.1.4 on 2021-01-30 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_quot_quoteauthor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='human',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='humanaddress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='humanaddress',
            name='human',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Human',
        ),
        migrations.DeleteModel(
            name='HumanAddress',
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
