# Generated by Django 3.1.4 on 2021-02-08 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100, unique=True, verbose_name='author')),
                ('born_in', models.CharField(max_length=100, verbose_name='born in')),
                ('date_of_birth', models.CharField(max_length=100, verbose_name='author')),
                ('description', models.CharField(max_length=10000, verbose_name='description')),
            ],
            options={
                'ordering': ['author', 'born_in'],
            },
        ),
        migrations.CreateModel(
            name='Quot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.quoteauthor')),
            ],
        ),
    ]
